version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/reddit_abuse
    depends_on:
      - db
    volumes:
      - ./data:/app/data
      - ./models:/app/models

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=reddit_abuse
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
